### ISSUE TITLE
jiti v2 roadmap

### ISSUE THREAD

**Issue by pi0** [unjs/jiti#174]
Jiti was created almost [3 years ago](https://github.com/unjs/jiti/commit/ae9eb72c52c07dbd6b91b22e14b1f3e8669be483) with the aim of bringing stable, compact and fast ESM (and later Typescript) support to all JavaScript runtimes.

Skipping years ahead, most of the recent Node.js versions has built-in ESM support and new runtimes (such as Deno and Bun), ship with native typescript even!

Jiti, today has an enormous 32M monthly downloads (❤️) nowadays (mainly Nuxt and Tailwind traffic i guess) and making breaking changes can affect the ecosystem.

My plan for v2 is to include more risky changes in it but also avoid API-breaking changes for Jiti v2 as much as possible to make migration smooth.

```[tasklist]
### Tasks
- [x] https://github.com/unjs/jiti/pull/240
- [x] https://github.com/unjs/jiti/pull/239
- [x] Add `exports` field
- [x] Enable ESMResolve by default
- [x] Leverage `import.meta.resolve` when available
- [ ] https://github.com/unjs/jiti/pull/158
- [ ] https://github.com/unjs/jiti/issues/32
```

**Comment by NamesMT** [comment]
Would be amazing if inheriting `tsconfig`'s aliases support could be added, like [tsx (esno)](https://github.com/privatenumber/tsx)

**Comment by AlemTuzlak** [comment]
Hi @pi0, would bundling this into esm be enough to make it work in ESM envs? I forked the project and semi created esm/cjs bundling. Would this be something you guys would be interested in?

**Comment by pi0** [comment]
Almost there! (feebacks welcome from nightly and beta releases!)
